name: Deploy Pipeline to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Notebook
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          # This authenticates with your secrets and pushes the code to your workspace
          # The target path now includes the .py extension to prevent the folder overwrite error
          databricks workspace import /Workspace/Users/udayshankar8991@gmail.com/01_My_First_Notebook.py --file ./01_My_First_Notebook.py --format SOURCE --overwrite
          
          echo "Deployment successful!"
